development:
  adapter: postgresql
  encoding: unicode
  database: boilerplate
  pool: 2
  username: boilerplate_user
  password: boilerplate_secret_password

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>